### ISSUE TITLE
ERROR: Conversation not found

### ISSUE THREAD

**Issue by IloveAI2023** [josStorer/chatGPTBox#311]
What does this mean? And how to solve the problem? Thank you!

錯誤:

{"detail":{"message":"Conversation not found","code":"history_disabled_conversation_not_found"}}

**Comment by josStorer** [comment]
In the latest version, when using web mode to chat, additional request parameters are added to inform OpenAI not to store chat records and not use data for training, in order to avoid users seeing a lot of "New Chat" when opening the official website and protect users' privacy. However, this will result in the conversation being unavailable after a period of time. For these conversations, you have to switch to gpt-3.5-turbo to continue the conversation. The API mode conversion is compatible.

![image](https://user-images.githubusercontent.com/13366013/236599184-ca774353-6904-40fd-ada7-1875e3e79628.png)

**Comment by IloveAI2023** [comment]
Thank you very much! I have switched to gpt-3.5-turbo and inserted the API key, however, a new error seems to appear as follows:

{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

**Comment by josStorer** [comment]
It seems that the free quota of your account has expired.

**Comment by flyingv523615** [comment]
I also got the "Conversation not found" message, but I would like to continue the conversation. I would be very happy if a workaround option is added.

**Comment by josStorer** [comment]
@IloveAI2023 @flyingv523615 
[v2.3.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.3.1)

![image](https://user-images.githubusercontent.com/13366013/236861927-34caac80-c6b9-4a19-985a-3ffd497aa804.png)

**Comment by EgbertVon-Dolst** [comment]
Hello! I would like to suggest somehow implementing the functionality in such a way that ChatGPT does not interrupt the narration at the previous session and does not start over, but continues to add the previous content ... And another question, is it possible to jailbreak bing AI?
