### ISSUE TITLE
breaks archwiki enumeration

### ISSUE THREAD

**Issue by kushagra-xo** [josStorer/chatGPTBox#538]
![image](https://github.com/josStorer/chatGPTBox/assets/106916795/237f15ef-297d-429f-8c4d-6c88f4c14f3c)

**Comment by kushagra-xo** [comment]
everything is changed to 1

works as expected when not using chatgptbox 

url: https://wiki.archlinux.org/title/Arch_Linux

**Comment by josStorer** [comment]
The reason for this problem is that the `counter-reset` style of the page `body` is disabled when the addon activated, but I have not found an effective solution yet. Even if I try to disable all styles of chatgptbox, the problem still exists.

I think it may be related to the implementation of `counter-reset` in Firefox. I believe `counter-reset` is still unstable. I found a discussion that may be relevant: https://github.com/w3c/csswg-drafts/issues/5477 and some other thing: https://stackoverflow.com/questions/70877408/css-counter-continues-counting-in-firefox

**Comment by kushagra-xo** [comment]
can this be fixed? the only thing thats keeping me from using this extension

**Comment by josStorer** [comment]
@kushagra-xo Have found a solution, I think I will fix it in the next version.

**Comment by kushagra-xo** [comment]
thank you very much :)

**Comment by josStorer** [comment]
fixed in [v2.5.1](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.1)

**Comment by kushagra-xo** [comment]
many thanks.
