### ISSUE TITLE
Support for Ollama

### ISSUE THREAD

**Issue by Mulugruntz** [josStorer/chatGPTBox#616]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**
When trying to have the extension target my local Mistral handled by Ollama, it fails (HTTP 403).
![image](https://github.com/josStorer/chatGPTBox/assets/13810199/f516a1bb-c0c6-4ef3-a076-c91f054e35b3)

The settings:
![image](https://github.com/josStorer/chatGPTBox/assets/13810199/7d4b6dff-f07b-44a0-9da7-d9ca7d4fdab2)
I haven't digged into the code yet, but maybe it's because it uses a different API.

Can see here that Ollama WebUI works as expected
![image](https://github.com/josStorer/chatGPTBox/assets/13810199/77341af0-9629-477e-894d-a17196f97435)

and that Ollama is running
![image](https://github.com/josStorer/chatGPTBox/assets/13810199/02702336-ca22-4e8b-adfb-c99248c39241)

**Describe the solution you'd like**
**你期望的新功能实现方案**
ChatGPTBox to work with Ollama.

**Additional context**
**其他**
Yes, see above :).

**Comment by josStorer** [comment]
Could you please capture the request through F12 Network in the Ollama WebUI, and provide the relevant request headers and body

**Comment by Donno191** [comment]
It would be nice to use ollama ! Maybe it works with the support of ollama openai api ? Example of settings ?

**Comment by josStorer** [comment]
After consulting the documentation of ollama, I found that ollama provides APIs compatible with OpenAI API.

And for the 403 error, it is actually caused by cross-origin requests. According to https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-allow-additional-web-origins-to-access-ollama, you can set environment variable `OLLAMA_ORIGINS` to `*`, and then restart ollama to allow requests from browser extensions.

The settings of ChatGPTBox are as follows:
![image](https://github.com/josStorer/chatGPTBox/assets/13366013/dbba9ee2-9ea1-4ef9-a6f4-00338cabd553)

**Comment by BarfingLemurs** [comment]
thanks for the tip, filling the model name eg: "gemma:2b" is a requirement for ollama to works, along with: `export OLLAMA_ORIGINS=*` on linux.

**Comment by Katzenwerfer** [comment]
Something to note.
Setting origins with a wildcard is generally not recommended.
It is better to be specific and ideally add `moz-extension://[ID OF THE EXTENSION]`, or with a wildcard if you can't find the ID `moz-extension://*`

**Comment by lrq3000** [comment]
For reference, the issue was discussed here on the ollama issues tracker:

* https://github.com/ollama/ollama/issues/2425

For better security, it was suggested [here](https://github.com/ollama/ollama/issues/2335) to set the var to the following:

```OLLAMA_ORIGINS=chrome-extension://* ollama serve```

Note that on Windows you need to logout and log back in, or restart the computer, for the environment variable change to take effect. If you want to try asap, you can instead kill ollama, then open a command line terminal and write:

```set OLLAMA_ORIGINS=*
ollama serve```

This will temporarily allow cross origin access. But this won't persist, if you want a permanent environment change, use instead:

```setx OLLAMA_ORIGINS *```

Of course you need to have downloaded a model in ollama beforehand (eg, ```ollama run phi3.5```).
