### ISSUE TITLE
[Docs]: How about adding more docs about the integration for various commonly used websites

### ISSUE THREAD

**Issue by tianzhich** [josStorer/chatGPTBox#619]
This project is so cool, I also saw that it has made deep customizations for many websites, but I don't know how to use them on these websites. Can we add more documents or videos?

Thank you!

**Comment by josStorer** [comment]
Currently, support for various websites is automated. If a site is supported, you will see the ChatGPTBox component on the page; otherwise, it means the site is not supported. Custom site support cannot be added at the moment unless you modify the source code here: https://github.com/josStorer/chatGPTBox/tree/master/src/content-script/site-adapters

**Comment by tianzhich** [comment]
I see. So, in terms of functionality, the only feature is the summary page, right?
