### ISSUE TITLE
Custom user tools for text selection on page

### ISSUE THREAD

**Issue by janvarev** [josStorer/chatGPTBox#673]
**Is your feature request related to a problem? Please describe.**
I wanna have custom tools for text selection on page to process them in my own way (rephrase, short analytics etc.). It'll be very cool!

**Describe the solution you'd like**
I see solution like this:
1. Add up to 3-10 (up to author) buttons in tools for text selection. They can look in menu just like neutral icon numbers 1,2,3 etc. - they are custom user tools.
2. In extension settings there are the same (3-10) number of options, where prompt for this tool is describen in format like
`Paraphrase this text: {selectionText}. Answer always in {prefLanguage}` - with template vars in { } or something like that.
3. User tools can be enabled the same way as usual tools.

Hope it'll be not so hard to implement! Thanks a lot if you'll do it!

**Comment by janvarev** [comment]
Note: seems something similar was implemented in https://github.com/zwongstjude/chatGPTBox/commit/8b307556f66be10d56c71615151367f377a7d273

**Comment by josStorer** [comment]
[v2.5.6](https://github.com/josStorer/chatGPTBox/releases/tag/v2.5.6)

The Plugin System I envisioned previously is somewhat complex, and due to my limited time and energy, I am unable to implement it temporarily. However, considering that many users require custom prompt functionality, I have now implemented a simplified version. The implementation of this feature is not complex, but it had been missing for the past year, for which I apologize.

Simple custom selection tools is now supported

<img src="https://github.com/josStorer/chatGPTBox/assets/13366013/ff3de914-c53d-4a56-a2ff-d7f64fad7979" width="256"/> <img src="https://github.com/josStorer/chatGPTBox/assets/13366013/056c53d5-ce3d-42fd-aeb9-4930bc02fdc4" width="256"/>

**Comment by janvarev** [comment]
It's great! Thanks a lot for your work!
